services:
  bot:
    image: telegram-airdop-bot
    volumes:
      - /home/ec2-user/sessions:/app/sessions
    command: python3 main.py
    tty: true
    stdin_open: true
    develop:
      watch:
        - action: sync
          path: .
          target: /app
