apps = ['blum', 'coinsweeper', 'notpixel', 'okxracer', 'seed']
sessions = ['test', 'mrluas6']
multi_thread = true

[test]
skip_app = []

[mrluas6]
skip_app = ['blum', 'coinsweeper', 'notpixel', 'okxracer']
